test_notes_list_loginuser (
    notes.tests.test_content.TestNotesList.test_notes_list_loginuser
    ) ... [[{'True': True, 'False': False, 'None': None},
             {'csrf_token': <SimpleLazyObject: <function csrf.
              <locals>._get_val at 0x000001DDF6916C00>>, 
              'request': <WSGIRequest: GET '/notes/'>, 
              'user': <SimpleLazyObject: <User: Комментатор>>, 
              'perms': <django.contrib.auth.context_processors.PermWrapper 
              object at 0x000001DDF67A1D50>, 
              'messages': <django.contrib.messages.storage.fallback.FallbackStorage 
              object at 0x000001DDF67E9490>, 
              'DEFAULT_MESSAGE_LEVELS': {
                  'DEBUG': 10, 'INFO': 20,
                  'SUCCESS': 25, 'WARNING': 30,
                  'ERROR': 40}
                  }, {}, 
                {'paginator': None, 'page_obj': None, 
                'is_paginated': False, 
                'object_list': <QuerySet [<Note: Тестовая заметка>]>, 
                'note_list': <QuerySet [<Note: Тестовая заметка>]>, 
                'view': <notes.views.NotesList object at 0x000001DDF67FCED0>}], 
                [{'True': True, 'False': False, 'None': None}, 
                 {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x000001DDF6916C00>>, 
                  'request': <WSGIRequest: GET '/notes/'>, 'user': <SimpleLazyObject: <User: Комментатор>>, 
                  'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x000001DDF67A1D50>, 
                  'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x000001DDF67E9490>, 
                  'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, 
                  {}, {'paginator': None, 'page_obj': None, 
                       'is_paginated': False, 
                       'object_list': <QuerySet [<Note: Тестовая заметка>]>, 
                       'note_list': <QuerySet [<Note: Тестовая заметка>]>, 
                       'view': <notes.views.NotesList object at 0x000001DDF67FCED0>}], 
                       [{'True': True, 'False': False, 'None': None}, 
                        {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x000001DDF6916C00>>, 
                         'request': <WSGIRequest: GET '/notes/'>, 
                         'user': <SimpleLazyObject: <User: Комментатор>>, 
                         'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x000001DDF67A1D50>, 
                         'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x000001DDF67E9490>, 
                         'DEFAULT_MESSAGE_LEVELS': {
                             'DEBUG': 10, 
                             'INFO': 20, 
                             'SUCCESS': 25, 
                             'WARNING': 30, 
                             'ERROR': 40}
                             },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {}, {'paginator': None, 'page_obj': None, 'is_paginated': False, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'object_list': <QuerySet [<Note: Тестовая заметка>]>, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'note_list': <QuerySet [<Note: Тестовая заметка>]>, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'view': <notes.views.NotesList object at 0x000001DDF67FCED0>}, {}]]